#!/usr/bin/env python3

''' Check whether the required channels for each type of denoising (requested in order of preference) is present to save a SM stream to miniseed as waveform denoised to the greatest level of preference with the necessary channels present.
'''

'''
ATaCR controller code | wrapper scripts for ATaCR as implemented by OBSTools
    Copyright (C) 2026 Yingbo Li

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

from obspy import *
import numpy as np
import json
import os

from identify_seismem import SeisMem

def merge_paired_list_by_gap(l,tolerance):
    ''' Merge list with sequential pairs (representing ranges) of monotonically increasing values. "Merging" refers to combining two successive ranges into one range if the difference between the upper end of the first range and the lower end of the second range is smaller than the supplied tolerance. Multiple pairs can be combined if the gap between the individual ranges are all below tolerance.

    l         | <list>  | list of monotonically increasing paired values that represent ranges.
    tolerance | <float> | critical value to allow merging of successive ranges.

    Returns: <list> | merged list of monotonically increasing paired values that represent ranges.
    '''
    # Compute differences/gaps between successive pairs/ranges.
    gaps = [l[i+1][0]-l[i][1] for i in range(len(l)-1)]
    # Make sure that iteration finishes across the entirety of list l, with the final pair not being left out.
    gaps += [tolerance*2]
    # List to store merged ranges.
    merged = list()
    # Initialise counters to keep track of the current starting and ending indices.
    idx_start,idx_end = 0,0
    # Iterate through gaps between ranges.
    for i,gap in enumerate(gaps):
        # Check whether the gap is above tolerance.
        if gap >= tolerance:
            # If so, merge all pairs between the previously merged range (or the zeroth element if none before) and current index.
            merged.append([l[idx_start][0],
                           l[idx_end][1]
                           ])
            # Reset the start of the next merge.
            idx_start = i+1
        # Reset the index up to which pair merging is to happen.
        idx_end = i+1
    return merged

class CoverageChecker():
    def __init__(self,coverage,tolerance_seconds=0.5):
        '''
        Note: a very specific format for coverage is required (as generated by identify_coverage.py):
        {"<year>-<day>":{"<sta>":[[start0,end0],[start1,end1]]},
                        {"<sta>":...},
         "<year>-<day>":...
        }
        Where start and end are parsable by UTCDateTime and represent the time range of recorded waveform sections.

        '''
        self.coverage = coverage
        self.tolerance_seconds = tolerance_seconds
    def check_recorded(self,start,end,sta):
        ''' Check whether a time range is recorded across an unbroken (at least within tolerance) section of waveform for a given station.

        start | <obspy.core.utcdatetime.UTCDateTime> | start of the time range to check
        end   | <obspy.core.utcdatetime.UTCDateTime> | end of the time range to check
        sta   | <str>                                | name of station (must be in the coverage data)

        Returns: <bool> | which the time range is recorded across an unbroken section of waveform
        '''
        # Identify the keys to check the time range over.
        k0 = "%u-%03d" % (start.year,start.julday)
        k1 = "%u-%03d" % (end.year,end.julday)
        # Identify the relevant coverage lists to check for a continuous recording time over. "Local" refers to the the list of coverages being restricted to the relevant time for the requested time range.
        local_coverage = self.coverage[k0][sta]
        if k1 != k0:
            local_coverage.extend(self.coverage[k1][sta])
        # Merge all coverages (individual recording ranges) given some (small) tolerance for recording gaps.
        local_coverage = [[UTCDateTime(l[0]),UTCDateTime(l[1])] for l in local_coverage]
        merged_coverage = merge_paired_list_by_gap(local_coverage,self.tolerance_seconds)
        # Check whether the requested time range is within recording range for all of them.
        within_range = [((start+self.tolerance_seconds) >= c[0] and (end-self.tolerance_seconds) <= c[1]) for c in merged_coverage]
        # Identify if being within range is the case by checking if this is true for at least one recording range (it's exactly one recording range but this is shorter code).
        return any(within_range)

def seismem2mseed_atacr(atacr_path,denoise_preferences,
                        start_time_offset=0,end_time_offset=0,
                        out_dir="denoised-miniseeds"):
    ''' Write the most suitable denoise type from a SeisMem collection of streams to miniseed. Suitability is a balance between the order of denoise preferences and whether the denoise type is valid (i.e. the necessary channels were all present within the requested time range, which can be narrower than the start and end).

    atacr_path          | <str>          | path to folder generated by 12_process_event.py that contains SeisMem jsons.
    outfolder           | <str>          | folder to save miniseeds to.
    denoise_preferences | <list> [<str>] | list of denoise types (string in between the time and channel in EVENTS/<sta>/CORRECTED e.g. day.ZP-21) in preference order (preferred earlier). These types must be present as keys of `required_channels`.
    start_time_offset   | <float>        | time offset from the start of the trace to start checking for recording coverage.
    end_time_offset     | <float>        | time offset from the end of the trace to end checking for recording coverage. This offset is added to the end time so must be negative.
    out_dir             | <str>          | directory to save miniseed collections to.
    '''
    required_channels = {"og":["Z"],
                         "day.ZP":["Z","P"],
                         "sta.ZP":["Z","P"],
                         "day.ZP-H":["Z","P","2","1"],
                         "day.ZP-21":["Z","P","2","1"],
                         "sta.ZP-21":["Z","P","2","1"],
                         }
    # Identify the coverage files and initiate channel coverage checking objects.
    coverage_checkers = list()
    for cha in ["Z","H","1","2"]:
        with open("%s-covered.json" % cha) as infile:
            coverage_checkers.append(CoverageChecker(json.load(infile)))
    coveragechecker_z,coveragechecker_p,coveragechecker_1,coveragechecker_2 = coverage_checkers
    coverage_checking_map = {"Z":coveragechecker_z,
                             "P":coveragechecker_p,
                             "1":coveragechecker_1,
                             "2":coveragechecker_2,
                             }
    # Identify all json files to load as SeisMem collections.
    load_json = [os.path.join(atacr_path,f) for f in os.listdir(atacr_path) if f.endswith(".json")]
    # Iterate through json files.
    for json_f in load_json:
        # Setup folder to save miniseeds to.
        ev_name = os.path.basename(json_f).replace(".json","")
        out_folder = os.path.join(out_dir,ev_name)
        if not os.path.exists(out_folder):
            os.makedirs(out_folder,exist_ok=True)
        # Load json.
        SM_tmp = SeisMem(json_f)
        # Identify all steam types (denoise types and stations) in collection.
        keys = SM_tmp.storage.keys()
        # Construct address mapping with station name keys.
        sta_denoise_map = dict()
        for k in keys:
            props = k.split("/")
            # Station name
            sta = props[1]
            if sta not in sta_denoise_map:
                sta_denoise_map[sta] = dict()
            sta_denoise_map[sta][k.split("/")[0]] = k
        # Get a list of stations for the active SeisMem collection.
        stas = sorted(set(sta_denoise_map.keys()))
        # Iterate through stations.
        for sta in stas:
            # Identify all denoise types available.
            sta_streams = sta_denoise_map[sta]
            # Mark station as requiring analysis (to identify the most suitable denoise type).
            sta_processed = False
            # Iterate through the requested denoise types (provided in order of descending preference).
            for denoise_type in denoise_preferences:
                # Check if the most suitable denoise type has yet to be identified for the active station, and that the station has a valid denoised waveform for the denoise type.
                if denoise_type in sta_streams and not sta_processed:
                    # Identify the stream corresponding to the active denoise type.
                    path = sta_streams[denoise_type]
                    st = SM_tmp.storage[path]
                    # Identify all channels that were recording across the requested time range.
                    recorded_chas = []
                    for required_cha in required_channels[denoise_type]:
                        coverage_checker = coverage_checking_map[required_cha]
                        if required_cha not in recorded_chas:
                            cha_recorded = coverage_checker.check_recorded(st[0].stats.starttime+start_time_offset,st[0].stats.endtime+end_time_offset,sta)
                            if cha_recorded:
                                recorded_chas.append(required_cha)
                    # If all required channels are present, accept the stream.
                    if not len(set(required_channels[denoise_type]) - set(recorded_chas)):
                        st.write(os.path.join(out_folder,"-".join([sta,denoise_type])+".mseed"))
                        sta_processed = True
            if not sta_processed:
                print("Failure to find any traces for",sta,"in",json_f)
    return

if __name__=="__main__":
    # The start and end time offsets here are to make sure there's recording for the waveform that actually gets adaptively stacked (i.e. t0-20 to t0+40 where the total trace lengths are t0-100 to t0+200).
    seismem2mseed_atacr("denoised-data",["day.ZP-21","day.ZP","og"],
                        start_time_offset=80,end_time_offset=-160,
                        out_dir="denoised-miniseeds"
                        )
